yara_rules_list = {
    'anti_vm_detect': "https://raw.githubusercontent.com/AlienVault-Labs/AlienVaultLabs/refs/heads/master/malware_rulesets/yara/vmdetect.yar",
    'anti_debug_vm': "https://raw.githubusercontent.com/Yara-Rules/rules/refs/heads/master/antidebug_antivm/antidebug_antivm.yar",
    'anti_debug_with_linux': "https://raw.githubusercontent.com/DarkenCode/yara-rules/refs/heads/master/antidebug.yar",
    'findcrypt3_crypto' : "https://raw.githubusercontent.com/polymorf/findcrypt-yara/master/findcrypt3.rules",
    'packers' : "https://raw.githubusercontent.com/Yara-Rules/rules/refs/heads/master/packers/packer.yar"
}

all_libsodium_functions = {
    'sodium_init': 'Initialise la bibliothèque libsodium',
    'crypto_secretbox_easy': 'Cryptographie symétrique - Chiffrement facile',
    'crypto_secretbox_open_easy': 'Cryptographie symétrique - Déchiffrement facile',
    'crypto_secretbox_detached': 'Cryptographie symétrique - Chiffrement détaché',
    'crypto_secretbox_open_detached': 'Cryptographie symétrique - Déchiffrement détaché',
    'crypto_stream_salsa20': 'Cryptographie symétrique - Flux Salsa20',
    'crypto_stream_salsa20_xor': 'Cryptographie symétrique - XOR Salsa20',
    'crypto_stream_chacha20': 'Cryptographie symétrique - Flux ChaCha20',
    'crypto_stream_chacha20_xor': 'Cryptographie symétrique - XOR ChaCha20',
    'crypto_box_keypair': 'Cryptographie asymétrique - Génération de paire de clés',
    'crypto_box_easy': 'Cryptographie asymétrique - Chiffrement facile',
    'crypto_box_open_easy': 'Cryptographie asymétrique - Déchiffrement facile',
    'crypto_box_detached': 'Cryptographie asymétrique - Chiffrement détaché',
    'crypto_box_open_detached': 'Cryptographie asymétrique - Déchiffrement détaché',
    'crypto_box_seal': 'Cryptographie asymétrique - Scellage de boîte',
    'crypto_box_seal_open': 'Cryptographie asymétrique - Ouverture de boîte scellée',
    'crypto_sign_keypair': 'Signatures - Génération de paire de clés',
    'crypto_sign': 'Signatures - Signer un message',
    'crypto_sign_open': 'Signatures - Vérifier une signature',
    'crypto_sign_detached': 'Signatures - Signer un message (détaché)',
    'crypto_sign_verify_detached': 'Signatures - Vérifier une signature (détachée)',
    'crypto_hash_sha256': 'Hashing - SHA-256',
    'crypto_hash_sha512': 'Hashing - SHA-512',
    'crypto_generichash': 'Hashing - Hashing générique',
    'crypto_generichash_init': 'Hashing - Initialiser le hashing générique',
    'crypto_generichash_update': 'Hashing - Mettre à jour le hashing générique',
    'crypto_generichash_final': 'Hashing - Finaliser le hashing générique',
    'crypto_auth': 'HMAC - Authentification',
    'crypto_auth_verify': 'HMAC - Vérification de l\'authentification',
    'crypto_kdf_keygen': 'KDF - Génération de clé',
    'crypto_kdf_derive_from_key': 'KDF - Dérivation de clé',
    'crypto_kx_keypair': 'KX - Génération de paire de clés',
    'crypto_kx_client_session_keys': 'KX - Clés de session client',
    'crypto_kx_server_session_keys': 'KX - Clés de session serveur',
    'crypto_pwhash': 'Password Hashing - Hashing de mot de passe',
    'crypto_pwhash_str': 'Password Hashing - Hashing de mot de passe avec chaîne',
    'crypto_pwhash_str_verify': 'Password Hashing - Vérification de mot de passe avec chaîne',
    'crypto_pwhash_scryptsalsa208sha256': 'Password Hashing - Scrypt Salsa20/8 SHA-256',
    'crypto_pwhash_scryptsalsa208sha256_str': 'Password Hashing - Scrypt Salsa20/8 SHA-256 avec chaîne',
    'crypto_pwhash_scryptsalsa208sha256_str_verify': 'Password Hashing - Vérification Scrypt Salsa20/8 SHA-256 avec chaîne',
    'randombytes_buf': 'Random Number Generation - Génération de bytes aléatoires',
    'randombytes_uniform': 'Random Number Generation - Génération de nombre uniforme aléatoire',
    'randombytes_random': 'Random Number Generation - Génération de nombre aléatoire',
    'randombytes_stir': 'Random Number Generation - Mélanger le générateur de nombres aléatoires',
    'randombytes_close': 'Random Number Generation - Fermer le générateur de nombres aléatoires',
    'sodium_memzero': 'Utilitaires - Effacer la mémoire',
    'sodium_mlock': 'Utilitaires - Verrouiller la mémoire',
    'sodium_munlock': 'Utilitaires - Déverrouiller la mémoire',
    'sodium_bin2hex': 'Utilitaires - Convertir binaire en hexadécimal',
    'sodium_hex2bin': 'Utilitaires - Convertir hexadécimal en binaire',
    'sodium_base64_encoded_len': 'Utilitaires - Longueur encodée en base64',
    'sodium_bin2base64': 'Utilitaires - Convertir binaire en base64',
    'sodium_base642bin': 'Utilitaires - Convertir base64 en binaire'
}

all_c_file_manipulation = {
    'fopen': 'Ouvre un fichier',
    'fclose': 'Ferme un fichier',
    'fread': 'Lit des données depuis un fichier',
    'fwrite': 'Écrit des données dans un fichier',
    'fseek': 'Déplace le curseur de lecture/écriture dans un fichier',
    'ftell': 'Renvoie la position actuelle du curseur de lecture/écriture dans un fichier',
    'rewind': 'Réinitialise le curseur de lecture/écriture au début du fichier',
    'fflush': 'Vide le tampon de sortie d\'un fichier',
    'fgetc': 'Lit un caractère depuis un fichier',
    'fputc': 'Écrit un caractère dans un fichier',
    'fgets': 'Lit une chaîne de caractères depuis un fichier',
    'fputs': 'Écrit une chaîne de caractères dans un fichier',
    'fscanf': 'Lit des données formatées depuis un fichier',
    'fprintf': 'Écrit des données formatées dans un fichier',
    'remove': 'Supprime un fichier',
    'rename': 'Renomme un fichier',
    'tmpfile': 'Crée un fichier temporaire',
    'tmpnam': 'Génère un nom de fichier temporaire unique',
    'setvbuf': 'Définit le mode de tampon d\'un fichier',
    'feof': 'Teste la fin de fichier',
    'ferror': 'Teste les erreurs de fichier',
    'clearerr': 'Réinitialise les indicateurs d\'erreur de fichier'
}

all_process_injection_functions = {
    'CreateRemoteThread': 'Crée un thread dans un processus distant',
    'VirtualAllocEx': 'Alloue de la mémoire dans un processus distant',
    'WriteProcessMemory': 'Écrit dans la mémoire d\'un processus distant',
    'QueueUserAPC': 'Ajoute une procédure à la file d\'attente d\'un thread distant',
    'NtCreateThreadEx': 'Crée un thread dans un processus distant (NT)',
    'RtlCreateUserThread': 'Crée un thread dans un processus distant (RTL)',
    'SetThreadContext': 'Modifie le contexte d\'un thread distant',
    'GetThreadContext': 'Récupère le contexte d\'un thread distant',
    'SuspendThread': 'Suspend un thread distant',
    'ResumeThread': 'Reprend un thread distant',
    'OpenProcess': 'Ouvre un processus distant',
    'LoadLibrary': 'Charge une bibliothèque dans un processus distant',
    'GetProcAddress': 'Récupère l\'adresse d\'une fonction dans une bibliothèque chargée',
    'FreeLibrary': 'Libère une bibliothèque chargée dans un processus distant',
    'CreateProcess': 'Crée un nouveau processus',
    'ShellExecute': 'Exécute un programme ou ouvre un fichier',
    'WinExec': 'Exécute un programme'
}

all_network_functions = {
    'socket': 'Crée un point de communication',
    'connect': 'Établit une connexion avec un serveur',
    'send': 'Envoie des données sur une connexion',
    'recv': 'Reçoit des données sur une connexion',
    'bind': 'Lie une adresse à un socket',
    'listen': 'Met le socket en mode écoute',
    'accept': 'Accepte une connexion entrante',
    'sendto': 'Envoie des données à une adresse spécifique',
    'recvfrom': 'Reçoit des données d\'une adresse spécifique',
    'shutdown': 'Arrête une connexion',
    'closesocket': 'Ferme un socket',
    'gethostbyname': 'Récupère l\'adresse IP d\'un nom d\'hôte',
    'getaddrinfo': 'Récupère les informations d\'adresse',
    'inet_addr': 'Convertit une adresse IP en format binaire',
    'inet_ntoa': 'Convertit une adresse IP en format texte',
    'WSAStartup': 'Initialise l\'utilisation de Winsock',
    'WSACleanup': 'Termine l\'utilisation de Winsock'
}

all_windows_encryption_functions = {
    'CryptAcquireContext': 'Acquiert un contexte de cryptographie',
    'CryptReleaseContext': 'Libère un contexte de cryptographie',
    'CryptGenKey': 'Génère une clé de cryptographie',
    'CryptDestroyKey': 'Détruit une clé de cryptographie',
    'CryptEncrypt': 'Chiffre des données',
    'CryptDecrypt': 'Déchiffre des données',
    'CryptImportKey': 'Importe une clé de cryptographie',
    'CryptExportKey': 'Exporte une clé de cryptographie',
    'CryptGenRandom': 'Génère des données aléatoires',
    'CryptHashData': 'Hache des données',
    'CryptCreateHash': 'Crée un objet de hachage',
    'CryptDestroyHash': 'Détruit un objet de hachage',
    'CryptSignHash': 'Signe un hachage',
    'CryptVerifySignature': 'Vérifie une signature',
    'CryptDeriveKey': 'Dérive une clé de cryptographie',
    'CryptDuplicateKey': 'Duplique une clé de cryptographie',
    'CryptSetKeyParam': 'Définit les paramètres d\'une clé de cryptographie',
    'CryptGetKeyParam': 'Récupère les paramètres d\'une clé de cryptographie',
    'CryptSetHashParam': 'Définit les paramètres d\'un objet de hachage',
    'CryptGetHashParam': 'Récupère les paramètres d\'un objet de hachage',
    'CryptDuplicateHash': 'Duplique un objet de hachage'
}

all_debug_detection_functions = {
    'IsDebuggerPresent': 'Détecte si un débogueur est présent',
    'CheckRemoteDebuggerPresent': 'Vérifie si un débogueur est présent dans un processus distant',
    'NtQueryInformationProcess': 'Récupère des informations sur un processus, y compris la présence d\'un débogueur',
    'OutputDebugString': 'Envoie une chaîne de caractères au débogueur',
    'GetThreadContext': 'Récupère le contexte d\'un thread, utilisé pour détecter les débogueurs',
    'SetUnhandledExceptionFilter': 'Définit une fonction de rappel pour les exceptions non gérées, souvent utilisé pour détecter les débogueurs',
    'UnhandledExceptionFilter': 'Fonction de rappel pour les exceptions non gérées, souvent utilisé pour détecter les débogueurs',
    'CloseHandle': 'Ferme un handle, utilisé pour détecter les débogueurs en fermant des handles critiques',
    'OpenProcess': 'Ouvre un processus, utilisé pour vérifier si un débogueur peut accéder au processus',
    'TerminateProcess': 'Termine un processus, utilisé pour détecter les débogueurs en tentant de terminer des processus critiques',
    'DebugActiveProcess': 'Attache un débogueur à un processus actif',
    'DebugActiveProcessStop': 'Détache un débogueur d\'un processus actif',
    'DebugBreak': 'Déclenche une interruption de débogage',
    'DebugBreakProcess': 'Déclenche une interruption de débogage dans un processus distant',
    'DebugSetProcessKillOnExit': 'Définit si le processus doit être tué lorsque le débogueur se détache',
    'DebugString': 'Envoie une chaîne de caractères au débogueur'
}